import { IconSitemap } from '@tabler/icons-react'
import { useLangStore } from '@/store/simulationStore'
import {
  PageContainer,
  ChapterTitle,
  SectionTitle,
  Prose,
  InfoBox,
  ConceptGrid,
  Divider,
  Table,
  SqlBlock,
} from '../../shared'

const T = {
  ko: {
    title: '본질 식별자와 인조 식별자',
    subtitle:
      '식별자를 선택할 때 업무에서 자연스럽게 존재하는 본질 식별자와, 식별을 위해 인위적으로 만든 인조 식별자 중 어느 것을 쓸지 결정해야 해요.',

    whatTitle: '두 식별자의 차이',
    whatDesc:
      '본질 식별자(Natural Key)는 업무 영역에서 이미 존재하는 의미 있는 값이에요. 반면 인조 식별자(Surrogate Key)는 순전히 식별 목적만을 위해 시스템이 만들어내는 값이에요.\n\n예를 들어 "직원"을 식별할 때 — 주민등록번호는 본질 식별자, 자동으로 증가하는 직원ID(1, 2, 3...)는 인조 식별자예요.',

    compareTitle: '본질 vs 인조 식별자 비교',
    compareHeaders: ['항목', '본질 식별자 (Natural Key)', '인조 식별자 (Surrogate Key)'],
    compareRows: [
      ['의미', '업무적 의미를 가짐', '의미 없는 순번·코드'],
      ['예시', '주민등록번호, ISBN, 사번', '자동증가 ID (1, 2, 3…)'],
      ['변경 가능성', '변경될 수 있음 (결혼·오류 등)', '거의 변경되지 않음'],
      ['길이', '길거나 복잡한 경우 많음', '짧고 단순 (숫자 1개)'],
      ['JOIN 성능', '문자열 비교로 느릴 수 있음', '숫자 비교로 빠름'],
      ['노출 위험', '개인정보 포함 가능', '개인정보 없음'],
      ['가독성', '값만 보면 의미 파악 가능', '값만 봐서는 의미 모름'],
    ],

    naturalProblemsTitle: '본질 식별자의 문제점',
    naturalProblemsDesc:
      '본질 식별자는 직관적이지만 실무에서 여러 문제를 일으켜요.',
    naturalProblems: [
      {
        icon: '🔄',
        title: '값 변경 문제',
        desc: '결혼으로 이름이 바뀌거나, 오류로 번호가 변경되면 참조하는 모든 FK도 함께 바꿔야 해요. 연쇄 업데이트가 발생해요.',
        color: 'rose',
      },
      {
        icon: '🔐',
        title: '보안·개인정보 문제',
        desc: '주민등록번호처럼 민감한 정보가 PK가 되면 로그, 감사 기록 등 곳곳에 노출돼요.',
        color: 'orange',
      },
      {
        icon: '🐌',
        title: '성능 문제',
        desc: '긴 문자열 PK는 인덱스 크기가 커지고, FK 조인 시 비교 비용이 높아져요.',
        color: 'amber',
      },
      {
        icon: '🧩',
        title: '복합 키 복잡성',
        desc: '본질 식별자가 단일 속성으로 안 되면 복합 PK를 쓰게 되고, 이를 참조하는 FK도 모두 복합이 돼요.',
        color: 'violet',
      },
    ],

    surrogateTitle: '인조 식별자 구현 방법 (Oracle)',
    surrogateDesc:
      'Oracle에서 인조 식별자를 만드는 두 가지 방법이에요.',
    surrogateSql: `-- 방법 1: SEQUENCE + DEFAULT
CREATE SEQUENCE seq_employee START WITH 1 INCREMENT BY 1;

CREATE TABLE employees (
  employee_id  NUMBER        DEFAULT seq_employee.NEXTVAL PRIMARY KEY,
  name         VARCHAR2(100) NOT NULL,
  emp_no       VARCHAR2(20)  NOT NULL UNIQUE  -- 본질 식별자는 UNIQUE로 유지
);

-- 방법 2: GENERATED AS IDENTITY (Oracle 12c+, 권장)
CREATE TABLE employees (
  employee_id  NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(100) NOT NULL,
  emp_no       VARCHAR2(20)  NOT NULL UNIQUE
);

-- 삽입 시 employee_id는 자동 생성
INSERT INTO employees (name, emp_no) VALUES ('김철수', 'EMP-2024-001');`,

    bestPracticeTitle: '실무 권장 패턴',
    bestPracticeDesc:
      '인조 식별자를 PK로 쓰면서, 본질 식별자는 UNIQUE 제약으로 유지하는 게 가장 많이 쓰이는 패턴이에요.',
    bestPracticeHeaders: ['컬럼', '역할', '제약'],
    bestPracticeRows: [
      ['employee_id', '인조 식별자 — 시스템 내부 PK', 'PRIMARY KEY, NOT NULL, 자동생성'],
      ['emp_no', '본질 식별자 — 업무용 사번', 'UNIQUE, NOT NULL'],
      ['ssn', '개인식별번호 — 법적 요구사항', 'UNIQUE, 암호화 저장 권장'],
    ],

    whenNaturalTitle: '본질 식별자가 적합한 경우',
    whenNaturalDesc:
      '항상 인조 식별자가 정답은 아니에요. 이런 경우엔 본질 식별자가 나을 수 있어요.',
    whenNaturalConcepts: [
      {
        icon: '🔤',
        title: '코드성 테이블',
        desc: "국가코드(KR, US), 통화코드(KRW, USD) 등 변경 가능성이 낮고 의미가 명확한 경우.",
        color: 'blue',
      },
      {
        icon: '📦',
        title: '복합 자연키가 안정적인 경우',
        desc: '(연도, 월, 부서코드)처럼 변경 없이 안정적으로 유지되는 복합 키.',
        color: 'emerald',
      },
    ],

    summary:
      '인조 식별자는 변경 불변성, 성능, 보안 측면에서 본질 식별자보다 대부분 유리해요. 실무에서는 인조 식별자를 PK로 쓰고, 본질 식별자는 UNIQUE 제약으로 관리하는 패턴을 권장해요. 단, 코드성 참조 테이블처럼 값이 안정적인 경우엔 본질 식별자도 좋은 선택이에요.',
  },

  en: {
    title: 'Natural vs. Surrogate Identifiers',
    subtitle:
      'When choosing an identifier, you must decide between a natural key (meaningful value that already exists in the business domain) and a surrogate key (an artificial value created purely for identification).',

    whatTitle: 'The Difference Between the Two',
    whatDesc:
      'A natural key is a meaningful value that already exists in the business domain. A surrogate key is a value generated by the system purely for the purpose of identification.\n\nFor example, when identifying an "Employee" — a Social Security Number is a natural key; an auto-incrementing EmployeeID (1, 2, 3…) is a surrogate key.',

    compareTitle: 'Natural Key vs. Surrogate Key',
    compareHeaders: ['Aspect', 'Natural Key', 'Surrogate Key'],
    compareRows: [
      ['Meaning', 'Carries business meaning', 'Meaningless sequence or code'],
      ['Examples', 'SSN, ISBN, employee number', 'Auto-increment ID (1, 2, 3…)'],
      ['Mutability', 'Can change (marriage, errors, etc.)', 'Almost never changes'],
      ['Length', 'Often long or complex', 'Short and simple (a single number)'],
      ['JOIN performance', 'String comparisons can be slow', 'Numeric comparisons are fast'],
      ['Exposure risk', 'May contain personal data', 'No personal data'],
      ['Readability', 'Value alone conveys meaning', 'Value alone is meaningless'],
    ],

    naturalProblemsTitle: 'Problems with Natural Keys',
    naturalProblemsDesc:
      'Natural keys are intuitive but can cause serious issues in practice.',
    naturalProblems: [
      {
        icon: '🔄',
        title: 'Value change cascades',
        desc: 'If a name changes due to marriage, or a number is corrected, every FK referencing it must also be updated — a cascade update.',
        color: 'rose',
      },
      {
        icon: '🔐',
        title: 'Security & privacy risk',
        desc: 'Sensitive data like SSNs used as PKs end up exposed in logs, audit trails, and everywhere else.',
        color: 'orange',
      },
      {
        icon: '🐌',
        title: 'Performance overhead',
        desc: 'Long string PKs bloat indexes and increase comparison cost in FK joins.',
        color: 'amber',
      },
      {
        icon: '🧩',
        title: 'Composite key complexity',
        desc: 'When no single natural attribute is sufficient, you need a composite PK — and every FK referencing it becomes composite too.',
        color: 'violet',
      },
    ],

    surrogateTitle: 'Implementing Surrogate Keys in Oracle',
    surrogateDesc:
      'Two ways to create surrogate keys in Oracle.',
    surrogateSql: `-- Option 1: SEQUENCE + DEFAULT
CREATE SEQUENCE seq_employee START WITH 1 INCREMENT BY 1;

CREATE TABLE employees (
  employee_id  NUMBER        DEFAULT seq_employee.NEXTVAL PRIMARY KEY,
  name         VARCHAR2(100) NOT NULL,
  emp_no       VARCHAR2(20)  NOT NULL UNIQUE  -- keep natural key as UNIQUE
);

-- Option 2: GENERATED AS IDENTITY (Oracle 12c+, recommended)
CREATE TABLE employees (
  employee_id  NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(100) NOT NULL,
  emp_no       VARCHAR2(20)  NOT NULL UNIQUE
);

-- employee_id is auto-generated on insert
INSERT INTO employees (name, emp_no) VALUES ('John Kim', 'EMP-2024-001');`,

    bestPracticeTitle: 'Recommended Pattern in Practice',
    bestPracticeDesc:
      'The most common pattern is to use a surrogate key as the PK while keeping the natural key as a UNIQUE constraint.',
    bestPracticeHeaders: ['Column', 'Role', 'Constraints'],
    bestPracticeRows: [
      ['employee_id', 'Surrogate key — internal system PK', 'PRIMARY KEY, NOT NULL, auto-generated'],
      ['emp_no', 'Natural key — business employee number', 'UNIQUE, NOT NULL'],
      ['ssn', 'Personal ID — legal requirement', 'UNIQUE, encrypted storage recommended'],
    ],

    whenNaturalTitle: 'When Natural Keys Make Sense',
    whenNaturalDesc:
      "Surrogate keys aren't always the right answer. Natural keys can be a better choice in these situations.",
    whenNaturalConcepts: [
      {
        icon: '🔤',
        title: 'Code/lookup tables',
        desc: 'Country codes (KR, US), currency codes (KRW, USD) — stable, meaningful, unlikely to change.',
        color: 'blue',
      },
      {
        icon: '📦',
        title: 'Stable composite natural keys',
        desc: 'Composite keys like (year, month, dept_code) that remain stable and never need to change.',
        color: 'emerald',
      },
    ],

    summary:
      'Surrogate keys are generally superior to natural keys in terms of immutability, performance, and security. The recommended practice is to use a surrogate key as the PK and maintain the natural key as a UNIQUE constraint. That said, natural keys are still a good choice for stable reference/code tables.',
  },
}

export function IdentifierTypeSection() {
  const lang = useLangStore((s) => s.lang)
  const t = T[lang]

  return (
    <PageContainer>
      <ChapterTitle
        icon={<IconSitemap size={36} stroke={1.5} className="text-indigo-500" />}
        title={t.title}
        subtitle={t.subtitle}
      />

      <SectionTitle>{t.whatTitle}</SectionTitle>
      <Prose>{t.whatDesc}</Prose>

      <Divider />

      <SectionTitle>{t.compareTitle}</SectionTitle>
      <Table headers={t.compareHeaders} rows={t.compareRows} />

      <Divider />

      <SectionTitle>{t.naturalProblemsTitle}</SectionTitle>
      <Prose>{t.naturalProblemsDesc}</Prose>
      <ConceptGrid items={t.naturalProblems} />

      <Divider />

      <SectionTitle>{t.surrogateTitle}</SectionTitle>
      <Prose>{t.surrogateDesc}</Prose>
      <div className="mt-4">
        <SqlBlock sql={t.surrogateSql} badge="DDL" badgeColor="blue" desc={lang === 'ko' ? 'Oracle 인조 식별자 생성 패턴' : 'Oracle surrogate key patterns'} />
      </div>

      <Divider />

      <SectionTitle>{t.bestPracticeTitle}</SectionTitle>
      <Prose>{t.bestPracticeDesc}</Prose>
      <Table headers={t.bestPracticeHeaders} rows={t.bestPracticeRows} />

      <Divider />

      <SectionTitle>{t.whenNaturalTitle}</SectionTitle>
      <Prose>{t.whenNaturalDesc}</Prose>
      <ConceptGrid items={t.whenNaturalConcepts} />

      <div className="mt-8">
        <InfoBox variant="summary">{t.summary}</InfoBox>
      </div>
    </PageContainer>
  )
}
